### ISSUE TITLE
Name with spaces

### ISSUE THREAD

**Issue by DroneTechTI** [ricardotx/qbittorrent_telegram_notification#3]
Hello congratulations for the script, I wanted to ask you why torrents downloaded with a space are not notified with the full name but only the first part of the name? How can this be solved? A thousand thanks

**Comment by rteixeirax** [comment]
The torrent name is provided by the qbittorrent as you can see [here](https://github.com/rteixeirax/qbittorrent_telegram_notification/blob/master/src/qbittorrent_telegram_notification.sh#L10). I don't do any data manipulation, that is out of the scope of this script. The goal is only getting the data that is provided by the qbittorrent and sending it to the telegram.
