### ISSUE TITLE
Torrents with spaces in the name do not display correctly in the notification

### ISSUE THREAD

**Issue by rb-26** [ricardotx/qbittorrent_telegram_notification#8]
If the torrent title has spaces, then it will only send the text up to the space in the notification. 
![Screenshot 2024-05-31 at 2 22 18 PM](https://github.com/rteixeirax/qbittorrent_telegram_notification/assets/22605077/14675055-3329-4d6d-ba9d-bac5f3ece33e)

**Comment by Xiseous** [comment]
Opened a Pull request but for the time being here https://github.com/Xiseous/qBittorent_Telegram_Notifications/tree/master

**Comment by Xiseous** [comment]
I've tested it with the longest name I could that is feasible and on a release.

**Comment by rteixeirax** [comment]
The @Xiseous PR #9 that fixes this issue was merged.
